name: url-shortener

services:
  db:
    image: postgres:18
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  cache:
    image: redis:8
    ports:
      - ${REDIS_PORT}:6379
